import { type NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// Handles token_hash confirmation links generated by the Supabase Send Email hook.
// The existing /auth/callback handles ?code= (PKCE flow); this handles ?token_hash=.

// `next` may arrive as an ABSOLUTE url — Supabase forwards whatever was passed as
// emailRedirectTo/redirectTo verbatim into the hook's `redirect_to`, and
// src/app/actions/auth.ts passes `${APP_URL}/auth/callback`. Naively doing
// `${origin}${next}` then yields "https://host" + "https://host/path", which
// parses without throwing to the garbage host "thryvegrowth.cohttps" and sends
// the user nowhere. Reduce anything same-origin to a path and reject the rest,
// which also makes this an open-redirect guard.
function safeNextPath(raw: string | null, origin: string): string {
  const fallback = "/dashboard";
  if (!raw) return fallback;
  // Already a relative path. Reject "//host" (protocol-relative → off-site).
  if (raw.startsWith("/") && !raw.startsWith("//")) return raw;
  try {
    const parsed = new URL(raw);
    if (parsed.origin === origin) return `${parsed.pathname}${parsed.search}`;
  } catch {
    // not a parseable URL — fall through
  }
  return fallback;
}

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url);
  const token_hash = searchParams.get("token_hash");
  const type = searchParams.get("type") as
    | "signup"
    | "recovery"
    | "email_change"
    | "invite"
    | "magiclink"
    | null;
  const next = safeNextPath(searchParams.get("next"), origin);

  if (token_hash && type) {
    const supabase = await createClient();
    const { error } = await supabase.auth.verifyOtp({ token_hash, type });

    if (!error) {
      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  return NextResponse.redirect(`${origin}/login?error=auth_callback_failed`);
}
